import 'dart:io';

import 'package:building_material_retail/domain/entities/product_variant.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_cropper/image_cropper.dart';
import 'package:image_picker/image_picker.dart';
import 'package:remove_diacritic/remove_diacritic.dart';

import '../../../domain/entities/product.dart';
import '../../utils/type.dart';
import '../../providers/providers.dart';

class AdminAddProductPage extends ConsumerStatefulWidget {
  const AdminAddProductPage({super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _AdminAddProductPageState();
}

class _AdminAddProductPageState extends ConsumerState<AdminAddProductPage> {
  final titleTextEditingController = TextEditingController();
  final priceEditingController = TextEditingController();
  final descriptionEditingController = TextEditingController();
  final brandTextEditingController = TextEditingController();
  String dropdownValue = types[0];

  // Add controllers for technical specs
  final widthController = TextEditingController();
  final lengthController = TextEditingController();
  final thicknessController = TextEditingController();
  final weightController = TextEditingController();
  final colorController = TextEditingController();
  final sizeController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    addProduct() async {
      final storage = ref.read(databaseProvider);
      final fileStorage = ref.read(storageProvider);
      final imageFile = ref.read(addImageProvider.notifier).state;

      if (storage == null || fileStorage == null) {
        print("Error: storage or fileStorage is null");
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("Error: storage or fileStorage is null"),
          ),
        );
        return;
      }

      final nameWithoutAccent =
          removeDiacritics(titleTextEditingController.text).toLowerCase();
      List<String> searchIndex = [];
      final words = nameWithoutAccent.split(" ");
      searchIndex.addAll(words);

      // Prepare technical specs map
      final technicalSpecs = {
        'width': widthController.text,
        'length': lengthController.text,
        'thickness': thicknessController.text,
        'weight': weightController.text,
      };

      // Prepare Product
      final product = Product(
        // id will be auto-generated by the database
        name: titleTextEditingController.text,
        unit: 'Cái', // or get from dropdown if you want dynamic
        category: dropdownValue,
        taxRate: null, // add a field/controller if you want to input this
      );

      Future<String?> addProductWithImageUrl() async {
        // Save product and get its id
        final productId = await storage.addProduct(product);
        return productId;
      }

      Future<void> addVariant(String productId) async {
        final price = double.tryParse(priceEditingController.text) ?? 0.0;
        final sku = '${titleTextEditingController.text}_${brandTextEditingController.text}'.replaceAll(' ', '_').toLowerCase();
        final variant = ProductVariant(
          productId: productId,
          sku: sku,
          basePrice: price,
          size: sizeController.text.isNotEmpty ? sizeController.text : null,
          color: colorController.text.isNotEmpty ? colorController.text : null,
          technicalSpecs: technicalSpecs,
        );
        await storage.addProductVariant(variant);
      }

      if (imageFile != null) {
        fileStorage.uploadFile(imageFile.path).then((imageUrl) async {
          print("Image URL: $imageUrl");
          final productId = await addProductWithImageUrl();
          if (productId != null) {
            await addVariant(productId);
          }
          Navigator.pop(context);
        });
      } else {
        final productId = await addProductWithImageUrl();
        if (productId != null) {
          await addVariant(productId);
        }
        Navigator.pop(context);
      }
    }

    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final borderColor = isDark ? Colors.grey[700]! : Colors.grey[300]!;
    final cardBg = isDark ? Colors.grey[900]! : Colors.white;
    final sectionHeaderStyle = theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold, color: Colors.blue[700]);
    final labelStyle = theme.textTheme.bodyLarge?.copyWith(fontWeight: FontWeight.bold, color: Colors.grey[800]);

    return Scaffold(
      backgroundColor: isDark ? Colors.grey[100] : const Color(0xFFF6F8FA),
      floatingActionButton: Padding(
        padding: const EdgeInsets.all(16.0),
        child: FloatingActionButton.extended(
          onPressed: addProduct,
          backgroundColor: Colors.blue[600],
          label: const Text('Thêm sản phẩm', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Colors.white)),
          icon: const Icon(Icons.add, color: Colors.white),
          elevation: 8,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      appBar: AppBar(
        title: const Text('Thêm sản phẩm', style: TextStyle(color: Color(0xFF1A202C))),
        backgroundColor: Colors.white,
        elevation: 4,
        iconTheme: const IconThemeData(color: Color(0xFF1A202C)),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          double horizontalPadding = constraints.maxWidth < 640 ? 8 : 32;
          return Padding(
            padding: EdgeInsets.symmetric(horizontal: horizontalPadding, vertical: 20.0),
            child: SingleChildScrollView(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  // Image Holder with elevation
                  Material(
                    elevation: 8,
                    borderRadius: BorderRadius.circular(20),
                    shadowColor: Colors.black.withOpacity(0.15),
                    child: Stack(
                      alignment: Alignment.center,
                      children: [
                        Consumer(
                          builder: (context, watch, child) {
                            final image = ref.watch(addImageProvider);
                            return AnimatedContainer(
                              duration: const Duration(milliseconds: 300),
                              height: 170,
                              width: 170,
                              decoration: BoxDecoration(
                                color: Colors.grey[100],
                                borderRadius: BorderRadius.circular(20),
                                border: Border.all(color: borderColor, width: 2),
                              ),
                              child: image == null
                                  ? Icon(Icons.image, size: 90, color: Colors.grey[300])
                                  : ClipRRect(
                                      borderRadius: BorderRadius.circular(20),
                                      child: Image.file(
                                        File(image.path),
                                        height: 170,
                                        width: 170,
                                        fit: BoxFit.cover,
                                      ),
                                    ),
                            );
                          },
                        ),
                        // Camera button overlay
                        Positioned(
                          bottom: 10,
                          right: 10,
                          child: Material(
                            color: Colors.white.withOpacity(0.95),
                            shape: const CircleBorder(),
                            elevation: 6,
                            child: InkWell(
                              borderRadius: BorderRadius.circular(28),
                              onTap: () async {
                                var pickedFile = await ImagePicker().pickImage(
                                  source: ImageSource.gallery,
                                );
                                if (pickedFile != null) {
                                  final croppedFile = await ImageCropper().cropImage(
                                    sourcePath: pickedFile.path,
                                    aspectRatio: const CropAspectRatio(ratioX: 1, ratioY: 1),
                                    compressFormat: ImageCompressFormat.jpg,
                                    compressQuality: 60,
                                  );
                                  if (croppedFile != null) {
                                    ref.watch(addImageProvider.notifier).state = croppedFile;
                                  }
                                }
                              },
                              child: Container(
                                height: 56,
                                width: 56,
                                alignment: Alignment.center,
                                child: const Icon(Icons.camera_alt, size: 32, color: Color(0xFF2563EB)),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 36),
                  // Product Info Card
                  Material(
                    elevation: 3,
                    borderRadius: BorderRadius.circular(18),
                    shadowColor: Colors.black.withOpacity(0.10),
                    child: Card(
                      color: cardBg,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(18),
                        side: BorderSide(color: borderColor, width: 1.2),
                      ),
                      elevation: 0,
                      child: Padding(
                        padding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 18.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(bottom: 8.0),
                              child: Text('Thông tin sản phẩm', style: sectionHeaderStyle),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: titleTextEditingController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  alignLabelWithHint: false,
                                  hintText: 'VD: Ván ép phủ phim 18 ly',
                                  suffixIcon: IconButton(
                                    icon: const Icon(Icons.clear),
                                    onPressed: () {
                                      titleTextEditingController.clear();
                                    },
                                  ),
                                  label: RichText(
                                    text: TextSpan(
                                      text: 'Tên sản phẩm ',
                                      style: labelStyle,
                                      children: const [
                                        TextSpan(
                                          text: '*',
                                          style: TextStyle(color: Colors.red, fontSize: 18.0),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: descriptionEditingController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  hintText: 'VD: Ván ép phủ phim 18 ly chống ẩm',
                                  label: RichText(
                                    text: TextSpan(
                                      text: 'Mô tả sản phẩm ',
                                      style: labelStyle,
                                      children: const [
                                        TextSpan(
                                          text: '*',
                                          style: TextStyle(color: Colors.red, fontSize: 18.0),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: priceEditingController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  hintText: 'Nhập giá sản phẩm',
                                  label: RichText(
                                    text: TextSpan(
                                      text: 'Giá sản phẩm ',
                                      style: labelStyle,
                                      children: const [
                                        TextSpan(
                                          text: '*',
                                          style: TextStyle(color: Colors.red, fontSize: 18.0),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                keyboardType: TextInputType.number,
                              ),
                            ),
                            const Divider(),
                            //Unit
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: Row(
                                children: [
                                  Expanded(
                                    flex: 3,
                                    child: Text('Đơn vị tính:', style: labelStyle),
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    flex: 2,
                                    child: DropdownButtonFormField(
                                      value: 'Cái',
                                      decoration: const InputDecoration(
                                        border: InputBorder.none,
                                        contentPadding: EdgeInsets.zero,
                                      ),
                                      items: const [
                                        DropdownMenuItem(value: 'Cái', child: Text('Cái')),
                                        DropdownMenuItem(value: 'Mét', child: Text('Mét')),
                                        DropdownMenuItem(value: 'Bao', child: Text('Mét vuông')),
                                      ],
                                      onChanged: (dynamic value) {},
                                    ),
                                  )
                                ],
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: brandTextEditingController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'Thương hiệu',
                                  labelStyle: labelStyle,
                                  hintText: 'VD: Hoa Sen',
                                ),
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: Row(
                                children: [
                                  Expanded(
                                    flex: 3,
                                    child: Text('Loại vật liệu:', style: labelStyle),
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    child: DropdownButtonFormField(
                                      value: dropdownValue,
                                      decoration: const InputDecoration(
                                        border: InputBorder.none,
                                        contentPadding: EdgeInsets.zero,
                                      ),
                                      onChanged: (String? newValue) {
                                        setState(() {
                                          dropdownValue = newValue!;
                                        });
                                      },
                                      items: types.map((String value) {
                                        return DropdownMenuItem(
                                          value: value,
                                          child: Text(value),
                                        );
                                      }).toList(),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: colorController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'Màu sắc',
                                  labelStyle: labelStyle,
                                  hintText: 'VD: Nâu, Trắng',
                                ),
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: sizeController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'Kích thước',
                                  labelStyle: labelStyle,
                                  hintText: 'VD: 1220x2440',
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(height: 36),
                  // Specifications Card
                  Material(
                    elevation: 3,
                    borderRadius: BorderRadius.circular(18),
                    shadowColor: Colors.black.withOpacity(0.10),
                    child: Card(
                      color: cardBg,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(18),
                        side: BorderSide(color: borderColor, width: 1.2),
                      ),
                      elevation: 0,
                      child: Padding(
                        padding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 18.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(bottom: 8.0),
                              child: Text('Thông số kỹ thuật', style: sectionHeaderStyle),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: widthController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'Chiều rộng',
                                  labelStyle: labelStyle,
                                  hintText: 'VD: 1220 mm',
                                ),
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: lengthController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'Chiều dài',
                                  labelStyle: labelStyle,
                                  hintText: 'VD: 2440 mm',
                                ),
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: thicknessController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'Độ dày',
                                  labelStyle: labelStyle,
                                  hintText: 'VD: 18 mm',
                                ),
                              ),
                            ),
                            const Divider(),
                            ListTile(
                              contentPadding: EdgeInsets.zero,
                              title: TextField(
                                controller: weightController,
                                style: theme.textTheme.bodyLarge,
                                decoration: InputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'Trọng lượng',
                                  labelStyle: labelStyle,
                                  hintText: 'VD: 30 kg',
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(height: 120),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
